//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nomer
    {
        public int id { get; set; }
        public int Nomer1 { get; set; }
        public string Price { get; set; }
        public string Bronirovanie { get; set; }
        public string Usluga { get; set; }
    }
}
