//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registr
    {
        public int id { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public int Admin { get; set; }
    
        public virtual Admin Admin1 { get; set; }
    }
}
